application: bunco
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico
  mime_type: image/x-icon
 
- url: /js/(.*)
  static_files: public/js/\1
  upload: public/js/(.*)  
 
- url: /image/(.*)
  static_files: public/image/\1
  upload: public/image/(.*)  
 
- url: /css/(.*)
  static_files: public/css/\1
  upload: public/css/(.*)  
 
- url: /.*
  script: main.py
